/*
Copyright (c) 2011, Remco Vermeulen
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    *   Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
    *   Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
    *   Neither the name of the VU Amsterdam nor the
        names of its contributors may be used to endorse or promote products
        derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Remco Vermeulen  BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef REIL_INSTRUCTION_TABLE_H
#define REIL_INSTRUCTION_TABLE_H

#include "reil.h"

reil_instruction reil_instruction_table[] =
{
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_ADD,   "ADD",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}}, REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_SUB,   "SUB",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_MUL,   "MUL",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_DIV,   "DIV",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_MOD,   "MOD",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_LSH,   "LSH",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_ARITHMETIC_INSTRUCTION,   REIL_RSH,   "RSH",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_BITWISE_INSTRUCTION,      REIL_AND,   "AND",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_BITWISE_INSTRUCTION,      REIL_OR,    "OR",       REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_BITWISE_INSTRUCTION,      REIL_XOR,   "XOR",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_INPUT2|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_DATATRANSFER_INSTRUCTION, REIL_LDM,   "LDM",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_DATATRANSFER_INSTRUCTION, REIL_STM,   "STM",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_DATATRANSFER_INSTRUCTION, REIL_STR,   "STR",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_CONDITIONAL_INSTRUCTION,  REIL_BISZ,  "BISZ",     REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_CONDITIONAL_INSTRUCTION,  REIL_JCC,   "JCC",      REIL_INSTRUCTION_FLAG_INPUT1|REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_OTHER_INSTRUCTION,        REIL_UNDEF, "UNDEF",    REIL_INSTRUCTION_FLAG_OUTPUT, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_OTHER_INSTRUCTION,        REIL_UNKN,  "UNKN",     REIL_INSTRUCTION_FLAG_NONE, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL},
    {REIL_OTHER_INSTRUCTION,        REIL_NOP,   "NOP",      REIL_INSTRUCTION_FLAG_NONE, 0, 0, {{REIL_OPERAND_TYPE_EMPTY,{{0}},REIL_OPERAND_FLAG_NONE}},  NULL}
};

#endif
